### ISSUE TITLE
State of this SDK?

### ISSUE THREAD

**Issue by AndrejMitrovic** [aljoscha/statefun-rust#14]
Hi @aljoscha!

At the company I work for we're evaluating whether we should use this SDK for implementing stateful functions in Rust. In particular we want to integrate with Flink rather than seek other solutions.

We're curious about the state of this Rust SDK, in particular:

- Which version of Apache Stateful Functions is statefun-rust known to work against? Based on the last commit date I assume it's one of: [v2.0.0](https://flink.apache.org/2020/04/07/stateful-functions-2.0-an-event-driven-database-on-apache-flink/) (April 2020), [v2.1.0](https://flink.apache.org/2020/06/09/stateful-functions-2.1.0-release-announcement/) (June 2020), or [v2.2.0](https://flink.apache.org/2020/09/28/stateful-functions-2.2.0-release-announcement/) (September 2020).
- Is this SDK still being actively maintained, or planned to be actively worked on in the near future? If not, do you know of any alternative Rust SDK for statefun?
- How feature complete is this Rust SDK compared to the officially supported SDKs for the last targeted release version?

Really appreciate all the work you've put into this. 

Cheers!

**Comment by AndrejMitrovic** [comment]
I see now it's based on `2.1.0`: https://github.com/aljoscha/statefun-rust/blob/a283332ff4b66509fea22447ac145dca1b15e745/statefun-greeter-example/Dockerfile.statefun#L3

**Comment by aljoscha** [comment]
hi!

> Is this SDK still being actively maintained, or planned to be actively worked on in the near future? If not, do you know of any alternative Rust SDK for statefun?

I'm afraid I don't have the time right now to work on this, and I have no plans for the near/far future. If you _are_ interested, I'd be happy to move the project over to new owners/maintainers!

> How feature complete is this Rust SDK compared to the officially supported SDKs for the last targeted release version?

At the time it was quite complete but I haven't followed Statefun development since then.

I did ask a friend of mine who might know more if he has additional pointers. I'll get back to you! 👋

**Comment by AndrejMitrovic** [comment]
Hi, thanks for the quick response!

I've already started some work on this just to see how easy it would be to adapt the SDK to v3.x. There's a few breaking changes to the proto definitions like the new `TypedValue` in place of the raw bytes as it was before. But this shouldn't be a blocker.

If I get the examples working I might submit a PR. Perhaps we can target an unstable branch for now.

> If you are interested, I'd be happy to move the project over to new owners/maintainers!

I'm not sure about project ownership, I'll have to discuss this internally with the team at a later point.

Cheers!

**Comment by aljoscha** [comment]
Also, you might be aware already, but there is a new company that folks are building based on Statefun ideas. It's very early but could be interesting for you: https://restate.dev/ (I'm not associated with the company, but I know people that are)

**Comment by AndrejMitrovic** [comment]
Hi @aljoscha,

Hope you're doing great.

We've been working on upgrading support of the SDK to v3 and are close to being done.

My team will help me review the work in progress, and once that's done we'll either submit a PR upstream (here), or perhaps maintain our own fork. We haven't decided on project ownership yet. I will let you know how those discussions go.

If you're curious the work so far has been included here: https://github.com/AndrejMitrovic/statefun-rust/pull/1

Cheers!

**Comment by AndrejMitrovic** [comment]
Closed with https://github.com/aljoscha/statefun-rust/pull/15
